#########################################
# Gaps setting
#########################################
gaps inner 10
gaps outer 10
gaps left 48
gaps top 40
gaps bottom 5

#########################################
# Window Border 
#########################################
default_border pixel 4
default_floating_border pixel 4

#########################################
# Color Theme
#########################################
# class                     border      backgr.     text    indicator   child_border
client.focused              #81a2be     #81a2be     #1d1f21 #b3d4db
client.unfocused            #373b41     #373b41     #A6A8A6 #FF0000
client.focused_inactive     #c0c0c9     #c0c0c9     #000000 #ffffff
client.urgent               #373b41     #cc6666     #ffffff #cc6666
client.placeholder          #000000     #0c0c0c     #ffffff #2255ff     #0c0c0c 

##########
# Fonts
##########

font pango:Source Han Sans TW Medium 12

###########################
# Title Bar Icon
###########################
for_window [all] title_window_icon yes
for_window [all] title_window_icon padding 5px


