#############################################
# Window Property Settings
#############################################

for_window [all] title_window_icon padding 5px
for_window [title="子母畫面"] floating disabled
for_window [title="檔案操作進度"] floating enabled
for_window [title="Steam Guard - "] floating enabled
for_window [class="Xfce4-appfinder"] floating enable
for_window [class="jetbrains-idea-ce" title="win0"] floating enable
for_window [title="Steam 收藏庫資料夾"] floating enable
for_window [class="Remontoire"] floating enable

#########################################
# Assing application to workspace
#########################################
assign [class="Firefox"]                 $workspace_2
assign [class="firefox"]                 $workspace_2
assign [class="Google-chrome"]           $workspace_2
assign [class="jetbrains-idea-ce"]       $workspace_3
assign [class="Postman"]                 $workspace_3
assign [class="Deadbeef"]                $workspace_4
assign [class="mpv"]                     $workspace_4
assign [class="Gthumb"]                  $workspace_4
assign [class="Gimp"]                    $workspace_4
assign [class="Thunar"]                  $workspace_5
assign [title="Minecraft Launcher"]      $workspace_6
assign [class="Steam"]                   $workspace_6
assign [title="Steam"]                   $workspace_6
assign [class="obs"]                     $workspace_11

for_window [class="Firefox"]             focus
for_window [class="firefox"]             focus
for_window [class="Google-chrome"]       focus
for_window [class="jetbrains-idea-ce"]   focus
for_window [class="Postman"]             focus
for_window [class="Deadbeef"]            focus
for_window [class="mpv"]                 focus
for_window [class="Gthumb"]              focus
for_window [class="Gimp"]                focus
for_window [class="Thunar"]              focus
for_window [title="Minecraft Launcher"]  focus
for_window [class="Steam"]               focus
for_window [title="Steam"]               focus
for_window [class="obs"]                 focus

for_window [class=Xfce4-appfinder] floating enable, sticky enable, move position 35 605

