workspace $workspace_1 output DisplayPort-0
workspace $workspace_2 output DisplayPort-0
workspace $workspace_3 output DisplayPort-0
workspace $workspace_4 output DisplayPort-0
workspace $workspace_5 output DisplayPort-0
workspace $workspace_6 output DisplayPort-0
workspace $workspace_7 output DisplayPort-0
workspace $workspace_8 output DisplayPort-0
workspace $workspace_9 output DisplayPort-0
workspace $workspace_0 output DisplayPort-0

workspace $workspace_11 output HDMI-A-0
workspace $workspace_12 output HDMI-A-0
workspace $workspace_13 output HDMI-A-0
workspace $workspace_14 output HDMI-A-0
workspace $workspace_15 output HDMI-A-0
workspace $workspace_16 output HDMI-A-0
workspace $workspace_17 output HDMI-A-0
workspace $workspace_18 output HDMI-A-0
workspace $workspace_19 output HDMI-A-0
workspace $workspace_20 output HDMI-A-0

workspace_auto_back_and_forth yes

