#!/bin/bash
# If remontoire is running, kill it.  Otherwise start it.

remontoire_PID=$(pidof remontoire)

if [ -z "$remontoire_PID" ]; then
    /usr/local/bin/remontoire -s $(printenv I3SOCK) -t /usr/local/share/remontoire/stylesheet.css &
else
    kill $remontoire_PID
fi
