#!/usr/bin/python

import subprocess

proc = subprocess.Popen(['radeontop', '-d', '-'],stdout=subprocess.PIPE)

for line in iter(proc.stdout.readline,''):
    message = str(line)
    if "gpu" in message:
        usage = message[33:].split(",")[0][:-2]
        print(usage + "%", flush = True)
