set $monitor_mode  "螢幕模式：(S) 單螢幕 (D) 雙螢幕 (V) 垂直螢幕"

mode $monitor_mode {
    bindsym s exec --no-startup-id ~/.config/scripts/monitor/singlePrimary.sh, mode "default", restart
    bindsym d exec --no-startup-id ~/.config/scripts/monitor/dual.sh, mode "default", restart
    bindsym v exec --no-startup-id ~/.config/scripts/monitor/singleVertical.sh, mode "default", restart
 
    bindsym Return  mode "default"               
    bindsym Escape  mode "default"               
}                                                

bindsym $super+m mode $monitor_mode
