set $power_mode    "電源選單：(L) 鎖定 / (E) 登出 / (S) 暫停 / (R) 重開 / (H) 關機"

mode $power_mode {
    bindsym l exec --no-startup-id xscreensaver-command -lock, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id loginctl suspend, mode "default"
    bindsym r exec --no-startup-id loginctl reboot, mode "default"
    bindsym h exec --no-startup-id loginctl poweroff, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $ctrl+$alt+BackSpace mode $power_mode

