set $resize_mode   "調整大小：(I) 高度增加 (K) 高度減少 (J) 寬度減少 (L) 寬度增加"

mode $resize_mode {
    bindsym j	    resize shrink width 10 px or 10 ppt
    bindsym k       resize shrink height 10 px or 10 ppt
    bindsym i       resize grow height 10 px or 10 ppt
    bindsym l       resize grow width 10 px or 10 ppt

    bindsym Left    resize shrink width 10 px or 10 ppt
    bindsym Down    resize grow height 10 px or 10 ppt
    bindsym Up      resize shrink height 10 px or 10 ppt
    bindsym Right   resize grow width 10 px or 10 ppt

    bindsym Return  mode "default"
    bindsym Escape  mode "default"
}

bindsym $super+r mode $resize_mode

