#########################################
# Application Launcher
#########################################

bindsym F1 exec --no-startup-id xfce4-terminal --drop-down
bindsym XF86Tools exec --no-startup-id ~/.config/scripts/remontoire/toggle.sh
bindsym $super+Escape exec --no-startup-id i3-sensible-terminal
bindsym $super+Return exec --no-startup-id rofi -terminal xfce4-terminal -show-icons -display-drun "   執行" -display-window "    切換視窗" -modi drun#window -sidebar-mode -show drun -line-padding 5
bindsym $super+Tab exec --no-startup-id rofi -terminal xfce4-terminal -show-icons -display-drun "   執行" -display-window "    切換視窗" -modi drun#window -sidebar-mode -show window -line-padding 5
bindsym Print exec --no-startup-id xfce4-screenshooter

