##########################################
# Window Navigation
##########################################

## 4. 視窗焦點 // 上下左右 // <Super> ↑ ↓ ← → ##
## 4. 視窗焦點 // 上下左右 // <Super> I K J L ##
## 4. 視窗焦點 // 到上一層 // <Super> P ##
bindsym $super+Up             focus up
bindsym $super+Down           focus down
bindsym $super+Left           focus left
bindsym $super+Right          focus right
bindsym $super+i              focus up
bindsym $super+k              focus down
bindsym $super+j              focus left
bindsym $super+l              focus right
bindsym $super+p              focus parent
bindsym $super+c              focus child

