bindsym $ctrl+$shift+i    resize grow height     15px 
bindsym $ctrl+$shift+k    resize shrink height   15px 
bindsym $ctrl+$shift+j    resize shrink width    15px 
bindsym $ctrl+$shift+l    resize grow width      15px 

