#########################################
# Layout Control
#########################################
 
## 3. 版面 // 頁籤模式 // <Super> T ##
## 3. 版面 // 磚塊模式 // <Super> E ##
## 3. 版面 // 水平切割 // <Super> H ##
## 3. 版面 // 垂直切割 // <Super> V ##
## 3. 版面 // 切換全螢幕 // <Super> f ##
## 3. 版面 // 切換浮動視窗 // <Super><Shift> f ##
 
bindsym $super+t layout tabbed
bindsym $super+e layout toggle split
bindsym $super+h split h
bindsym $super+v split v
bindsym $super+f fullscreen toggle
bindsym $super+$shift+f floating toggle

