#########################################
# Actions
#########################################
## 1. 動作 // 關閉程式 // <MOD> Q ##
## 1. 動作 // 關閉程式 // <Super> 中鍵 ##
## 1. 動作 // 重啟I3   // <Super> <Shift> R ##

bindsym --whole-window  $super+button2    kill
bindsym --whole-window  button10          kill

bindsym $super+q      kill
bindsym $super+$shift+r                   restart
bindsym $mod+Shift+c reload

