set $workspace_1 "1: [1]    一般 "
set $workspace_2 "2: [2]    瀏覽"
set $workspace_3 "3: [3]    開發"
set $workspace_4 "4: [4]    影音"
set $workspace_5 "5: [5]    檔案"
set $workspace_6 "6: [6]    遊戲"
set $workspace_7 "7: [7]    一般"
set $workspace_8 "8: [8]    一般"
set $workspace_9 "9: [9]    一般"
set $workspace_10 "10: [0]    一般"
set $workspace_11 "11: [F1]    直播"
set $workspace_12 "12: [F2]    外接螢幕"
set $workspace_13 "13: [F3]    外接螢幕"
set $workspace_14 "14: [F4]    外接螢幕"
set $workspace_15 "15: [F5]    外接螢幕"
set $workspace_16 "16: [F6]    外接螢幕"
set $workspace_17 "17: [F7]    外接螢幕"
set $workspace_18 "18: [F8]    外接螢幕"
set $workspace_19 "19: [F9]    外接螢幕"
set $workspace_20 "10: [10]    外接螢幕"

##########################################
# Workspace Navigation
##########################################
bindsym $alt+Left        workspace prev
bindsym $alt+Right       workspace next
bindsym $alt+j           workspace prev
bindsym $alt+l           workspace next

bindsym $alt+1		workspace $workspace_1
bindsym $alt+2          workspace $workspace_2
bindsym $alt+3          workspace $workspace_3
bindsym $alt+4          workspace $workspace_4
bindsym $alt+5          workspace $workspace_5
bindsym $alt+6          workspace $workspace_6
bindsym $alt+7          workspace $workspace_7
bindsym $alt+8          workspace $workspace_8
bindsym $alt+9          workspace $workspace_9
bindsym $alt+0          workspace $workspace_10
bindsym $alt+F1         workspace $workspace_11
bindsym $alt+F2         workspace $workspace_12
bindsym $alt+F3         workspace $workspace_13
bindsym $alt+F4         workspace $workspace_14
bindsym $alt+F5         workspace $workspace_15
bindsym $alt+F6         workspace $workspace_16
bindsym $alt+F7         workspace $workspace_17
bindsym $alt+F8         workspace $workspace_18
bindsym $alt+F9         workspace $workspace_19
bindsym $alt+F10        workspace $workspace_20

bindsym $super+$shift+o    move workspace to output right

