[colors]
background = #F21d1f21
foreground = #ffffff
disabled = #707880

[bottom/base]
scroll-up = "#i3.prev"
scroll-down = "#i3.next"
bottom = true
background = ${colors.background}
foreground = ${colors.foreground}
height = 34
padding-right = 5
modules-left = i3
modules-center = title
modules-right = gpu temperature_gpu_junction temperature_gpu_edge  cpu temperature_cpu

font-0 = "Source Han Sans TW Medium:style=Medium,Regular;5"
font-1 = "Source Han Sans HK Medium:style=Medium,Regular;5"
font-2 = "Source Han Sans CN Medium:style=Medium,Regular;5"
font-3 = "Source Han Sans JP Medium:style=Medium,Regular;5"
font-4 = "SauceCodePro Nerd Font Mono:pixelsize=20;7"
font-5 = "NotoColorEmoji:scale=10;5"
font-6 = "Font Awesome 6 Free"
font-7 = "SauceCodePro Nerd Font Mono:pixelsize=15;6"

separator = |
separator-foreground = ${colors.disabled}

module-margin-left = 3
module-margin-right = 3

underline-size = 3

monitor = ${env:MONITOR:}

[bar/mybar_DisplayPort-0]
inherit = bottom/base

[bar/mybar_HDMI-A-0]
inherit = bottom/base
modules-center = 

[module/title]
type = internal/xwindow
label = "󰆍 %title%"
label-maxlen = 50
label-empty = 未選取視窗

[module/gpu]
type = custom/script
exec = /home/brianhsu/.config/scripts/polybar/modules/radeon_gpu_usage.sh
tail = true
font = 7
label = " %output:0:15:...%"
format-prefix = "  "
format-prefix-foreground = #00FFFF

[module/cpu]
type = internal/cpu
format =%{A1:/home/brianhsu/.config/scripts/polybar/modules/start_htop.sh:} <label> <ramp-load> %{A}

label = "%percentage:4%% "
format-prefix = ""
; ramps for ramp-load
ramp-load-0 = ▁
ramp-load-1 = ▂
ramp-load-2 = ▃
ramp-load-3 = ▄
ramp-load-4 = ▅
ramp-load-5 = ▆
ramp-load-6 = ▇
ramp-load-7 = █
; colors for each ramp
ramp-load-0-foreground = #aaff77
ramp-load-1-foreground = #aaff77
ramp-load-2-foreground = #aaff77
ramp-load-3-foreground = #aaff77
ramp-load-4-foreground = #fba922
ramp-load-5-foreground = #fba922
ramp-load-6-foreground = #ff5555
ramp-load-7-foreground = #ff5555

[temperature/base]
type = internal/temperature
interval = 0.5

format = "<ramp>  <label>"
format-warn = "🔥  <ramp>  <label-warn>"

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = #f00

ramp-font = 8
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-0-foreground = #AAAAAA
ramp-1-foreground = #00DD00
ramp-2-foreground = #AADD00
ramp-3-foreground = #FFFF00
ramp-4-foreground = #FF0000

[module/temperature_cpu]
inherit = temperature/base

hwmon-path = /sys/class/hwmon/hwmon4/temp1_input

base-temperature = 40
warn-temperature = 80

[module/temperature_gpu_junction]
inherit = temperature/base

hwmon-path = /sys/class/hwmon/hwmon4/temp2_input

base-temperature = 50
warn-temperature = 80

format-prefix = "J  "

[module/temperature_gpu_edge]
inherit = temperature/base

hwmon-path = /sys/class/hwmon/hwmon4/temp1_input

base-temperature = 50
warn-temperature = 90

format-prefix = "E  "

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true

; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 3
label-mode-background = #900000

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-focused = %name%
label-focused-foreground = #ffffff
label-focused-background = #4f4f4f
label-focused-underline = #fba922
label-focused-padding = 3

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-unfocused = %name%
label-unfocused-padding = 3

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-visible = %name%
label-visible-padding = 3

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon%  %name%
label-urgent = %name%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 3

[settings]
screenchange-reload = true
pseudo-transparency = true
